import type { ProductEntity } from './entities/product.entity';

export type ProductSeed = Omit<ProductEntity, 'id' | 'createdAt' | 'updatedAt'>;

export const PRODUCT_SEEDS: ProductSeed[] = [
  {
    slug: 'cerave-hydrating-cleanser',
    name: 'CeraVe Hydrating Cleanser',
    brand: 'CeraVe',
    description: 'Nettoie sans décaper. Aide à préserver la barrière cutanée.',
    imagePath: '/public/products/cerave-hydrating-cleanser.svg',
    productType: 'cleanser',
    price: '129',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive', 'normal'],
    goals: ['hydration', 'barrier'],
    keyIngredients: ['Céramides', 'Acide hyaluronique', 'Glycérine'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['sans parfum', 'doux'],
    badges: ['Meilleur choix'],
    benefits: ['Nettoie sans décaper', 'Aide à préserver la barrière cutanée'],
    isActive: true,
  },
  {
    slug: 'cerave-foaming-cleanser',
    name: 'CeraVe Foaming Cleanser',
    brand: 'CeraVe',
    description: 'Nettoie l’excès de sébum. Respecte la barrière cutanée.',
    imagePath: '/public/products/cerave-foaming-cleanser.svg',
    productType: 'cleanser',
    price: '139',
    currency: 'MAD',
    skinTypes: ['oily', 'combination', 'normal'],
    goals: ['oil_control', 'acne'],
    keyIngredients: ['Céramides', 'Niacinamide', 'Glycérine'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['sans parfum', 'non comédogène'],
    badges: ['Peau grasse'],
    benefits: ['Nettoie l’excès de sébum', 'Respecte la barrière cutanée'],
    isActive: true,
  },
  {
    slug: 'laroche-effaclar-serum',
    name: 'Effaclar Serum Ultra Concentré',
    brand: 'La Roche-Posay',
    description: 'Cible les imperfections. Aide à lisser le grain de peau.',
    imagePath: '/public/products/laroche-effaclar-serum.svg',
    productType: 'serum',
    price: '210',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'oil_control', 'glow'],
    keyIngredients: ['Acide salicylique', 'Niacinamide', 'LHA'],
    watchoutIngredients: ['Acides exfoliants'],
    avoidFor: ['very-sensitive', 'retinol-beginner'],
    tags: ['anti-imperfections'],
    badges: ['Top pour l’acné'],
    benefits: ['Cible les imperfections', 'Aide à lisser le grain de peau'],
    isActive: true,
  },
  {
    slug: 'bioderma-sensibio-defensive',
    name: 'Sensibio Defensive Rich',
    brand: 'Bioderma',
    description:
      'Aide à calmer les sensations d’inconfort. Nourrit les peaux sensibles.',
    imagePath: '/public/products/bioderma-sensibio-defensive.svg',
    productType: 'moisturizer',
    price: '185',
    currency: 'MAD',
    skinTypes: ['sensitive', 'dry'],
    goals: ['redness', 'barrier', 'hydration'],
    keyIngredients: ['Carnosine', 'Vitamine E', 'Allantoïne'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['apaisant', 'barrière'],
    badges: ['Apaisant'],
    benefits: [
      'Aide à calmer les sensations d’inconfort',
      'Nourrit les peaux sensibles',
    ],
    isActive: true,
  },
  {
    slug: 'ordinary-niacinamide-zinc',
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    description: 'Aide à réguler la brillance. Unifie visiblement le teint.',
    imagePath: '/public/products/ordinary-niacinamide-zinc.svg',
    productType: 'serum',
    price: '95',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'oil_control', 'glow'],
    keyIngredients: ['Niacinamide', 'Zinc PCA'],
    watchoutIngredients: [],
    avoidFor: ['very-sensitive'],
    tags: ['léger', 'sébum'],
    badges: ['Éclat'],
    benefits: ['Aide à réguler la brillance', 'Unifie visiblement le teint'],
    isActive: true,
  },
  {
    slug: 'neutrogena-hydro-boost',
    name: 'Hydro Boost Water Gel',
    brand: 'Neutrogena',
    description:
      'Hydrate sans effet lourd. Texture fraîche pour routine matin.',
    imagePath: '/public/products/neutrogena-hydro-boost.svg',
    productType: 'moisturizer',
    price: '110',
    currency: 'MAD',
    skinTypes: ['normal', 'combination', 'dry'],
    goals: ['hydration'],
    keyIngredients: ['Acide hyaluronique', 'Glycérine'],
    watchoutIngredients: ['Parfum'],
    avoidFor: ['fragrance-sensitive'],
    tags: ['texture gel'],
    badges: ['Hydratation intense'],
    benefits: [
      'Hydrate sans effet lourd',
      'Texture fraîche pour routine matin',
    ],
    isActive: true,
  },
  {
    slug: 'svr-sebiaclear-gel',
    name: 'Sébium Gel Moussant',
    brand: 'SVR',
    description:
      'Nettoie les peaux à imperfections. Aide à limiter l’aspect brillant.',
    imagePath: '/public/products/svr-sebiaclear-gel.svg',
    productType: 'cleanser',
    price: '119',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'oil_control'],
    keyIngredients: ['Gluconolactone', 'Niacinamide'],
    watchoutIngredients: ['Parfum'],
    avoidFor: ['fragrance-sensitive'],
    tags: ['purifiant'],
    badges: ['Doux & efficace'],
    benefits: [
      'Nettoie les peaux à imperfections',
      'Aide à limiter l’aspect brillant',
    ],
    isActive: true,
  },
  {
    slug: 'avene-cicalfate',
    name: 'Cicalfate+ Crème Réparatrice',
    brand: 'Avène',
    description: 'Aide les peaux fragilisées. Conforte les zones sèches.',
    imagePath: '/public/products/avene-cicalfate.svg',
    productType: 'moisturizer',
    price: '155',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive'],
    goals: ['barrier', 'redness'],
    keyIngredients: ['Sucralfate', 'Zinc', 'Cuivre'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['réparateur', 'sans parfum'],
    badges: ['Barrière'],
    benefits: ['Aide les peaux fragilisées', 'Conforte les zones sèches'],
    isActive: true,
  },
  {
    slug: 'eucerin-oil-control-spf',
    name: 'Oil Control SPF50+',
    brand: 'Eucerin',
    description: 'Protège du soleil. Fini adapté aux peaux grasses.',
    imagePath: '/public/products/eucerin-oil-control-spf.svg',
    productType: 'spf',
    price: '165',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['oil_control', 'acne'],
    keyIngredients: ['L-Carnitine', 'Filtres UV'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['spf', 'matifiant'],
    badges: ['SPF mat'],
    benefits: ['Protège du soleil', 'Fini adapté aux peaux grasses'],
    isActive: true,
  },
  {
    slug: 'vichy-mineral-89',
    name: 'Minéral 89 Booster',
    brand: 'Vichy',
    description: 'Renforce l’hydratation. Se superpose facilement.',
    imagePath: '/public/products/vichy-mineral-89.svg',
    productType: 'serum',
    price: '190',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive', 'normal', 'combination'],
    goals: ['hydration', 'barrier'],
    keyIngredients: ['Acide hyaluronique', 'Eau volcanique'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['minimaliste', 'hydratant'],
    badges: ['Hydratation'],
    benefits: ['Renforce l’hydratation', 'Se superpose facilement'],
    isActive: true,
  },
  {
    slug: 'cerave-moisturizing-cream',
    name: 'CeraVe Moisturizing Cream',
    brand: 'CeraVe',
    description: 'Nourrit les peaux sèches. Soutient la barrière cutanée.',
    imagePath: '/public/products/cerave-moisturizing-cream.svg',
    productType: 'moisturizer',
    price: '145',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive', 'normal'],
    goals: ['hydration', 'barrier'],
    keyIngredients: ['Céramides', 'Acide hyaluronique'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['riche', 'sans parfum'],
    badges: ['Peau sèche'],
    benefits: ['Nourrit les peaux sèches', 'Soutient la barrière cutanée'],
    isActive: true,
  },
  {
    slug: 'paulas-choice-bha',
    name: 'Skin Perfecting 2% BHA',
    brand: 'Paula’s Choice',
    description: 'Aide à désobstruer les pores. Lisse le grain de peau.',
    imagePath: '/public/products/paulas-choice-bha.svg',
    productType: 'exfoliant',
    price: '310',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'oil_control', 'glow'],
    keyIngredients: ['Acide salicylique'],
    watchoutIngredients: ['BHA'],
    avoidFor: ['very-sensitive', 'retinol-beginner'],
    tags: ['exfoliant'],
    badges: ['Pores'],
    benefits: ['Aide à désobstruer les pores', 'Lisse le grain de peau'],
    isActive: true,
  },
  {
    slug: 'laroche-cicaplast-baume',
    name: 'Cicaplast Baume B5+',
    brand: 'La Roche-Posay',
    description:
      'Apaise les sensations d’inconfort. Protège la barrière cutanée.',
    imagePath: '/public/products/laroche-cicaplast-baume.svg',
    productType: 'moisturizer',
    price: '135',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive'],
    goals: ['barrier', 'redness'],
    keyIngredients: ['Panthénol', 'Madécassoside', 'Beurre de karité'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['réparateur', 'apaisant'],
    badges: ['Réparation'],
    benefits: [
      'Apaise les sensations d’inconfort',
      'Protège la barrière cutanée',
    ],
    isActive: true,
  },
  {
    slug: 'bioderma-sebium-hydra',
    name: 'Sébium Hydra',
    brand: 'Bioderma',
    description:
      'Hydrate les peaux asséchées par traitements. Conforte sans trop alourdir.',
    imagePath: '/public/products/bioderma-sebium-hydra.svg',
    productType: 'moisturizer',
    price: '145',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'hydration', 'barrier'],
    keyIngredients: ['Glycérine', 'Céramides'],
    watchoutIngredients: ['Parfum'],
    avoidFor: ['fragrance-sensitive'],
    tags: ['hydratant', 'anti-dessèchement'],
    badges: ['Post-acné'],
    benefits: [
      'Hydrate les peaux asséchées par traitements',
      'Conforte sans trop alourdir',
    ],
    isActive: true,
  },
  {
    slug: 'ordinary-hyaluronic-acid',
    name: 'Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    description:
      'Augmente l’hydratation de surface. Simple à intégrer dans une routine.',
    imagePath: '/public/products/ordinary-hyaluronic-acid.svg',
    productType: 'serum',
    price: '99',
    currency: 'MAD',
    skinTypes: ['dry', 'normal', 'combination', 'sensitive'],
    goals: ['hydration'],
    keyIngredients: ['Acide hyaluronique', 'Panthénol'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['hydratant', 'simple'],
    badges: ['Hydratation'],
    benefits: [
      'Augmente l’hydratation de surface',
      'Simple à intégrer dans une routine',
    ],
    isActive: true,
  },
  {
    slug: 'isispharma-ruboril',
    name: 'Ruboril Expert M',
    brand: 'ISISPHARMA',
    description: 'Cible les rougeurs visibles. Texture adaptée au quotidien.',
    imagePath: '/public/products/isispharma-ruboril.svg',
    productType: 'moisturizer',
    price: '175',
    currency: 'MAD',
    skinTypes: ['sensitive', 'normal'],
    goals: ['redness'],
    keyIngredients: ['Ruscus', 'Esculoside'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['rougeurs'],
    badges: ['Rougeurs'],
    benefits: ['Cible les rougeurs visibles', 'Texture adaptée au quotidien'],
    isActive: true,
  },
  {
    slug: 'cerave-resurfacing-retinol',
    name: 'Resurfacing Retinol Serum',
    brand: 'CeraVe',
    description: 'Aide l’apparence des marques. À introduire progressivement.',
    imagePath: '/public/products/cerave-resurfacing-retinol.svg',
    productType: 'serum',
    price: '210',
    currency: 'MAD',
    skinTypes: ['oily', 'combination', 'normal'],
    goals: ['acne', 'glow', 'anti_age'],
    keyIngredients: ['Rétinol', 'Niacinamide', 'Céramides'],
    watchoutIngredients: ['Rétinol'],
    avoidFor: ['pregnancy', 'very-sensitive', 'retinol-beginner'],
    tags: ['texture', 'post-imperfections'],
    badges: ['Rétinol doux'],
    benefits: ['Aide l’apparence des marques', 'À introduire progressivement'],
    isActive: true,
  },
  {
    slug: 'uriage-bariederm-cica',
    name: 'Bariéderm Cica-Crème',
    brand: 'Uriage',
    description:
      'Protège les zones fragilisées. Aide au confort des peaux sensibilisées.',
    imagePath: '/public/products/uriage-bariederm-cica.svg',
    productType: 'moisturizer',
    price: '120',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive'],
    goals: ['barrier', 'redness'],
    keyIngredients: ['Cu-Zn', 'Poly-2P'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['cica', 'réparateur'],
    badges: ['Cica'],
    benefits: [
      'Protège les zones fragilisées',
      'Aide au confort des peaux sensibilisées',
    ],
    isActive: true,
  },
  {
    slug: 'avene-cleanance-gel',
    name: 'Cleanance Gel Nettoyant',
    brand: 'Avène',
    description:
      'Nettoie les peaux grasses. Aide à garder une sensation fraîche.',
    imagePath: '/public/products/avene-cleanance-gel.svg',
    productType: 'cleanser',
    price: '125',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'oil_control'],
    keyIngredients: ['Eau thermale', 'Zinc'],
    watchoutIngredients: ['Parfum'],
    avoidFor: ['fragrance-sensitive'],
    tags: ['nettoyant', 'sébum'],
    badges: ['Cleanance'],
    benefits: [
      'Nettoie les peaux grasses',
      'Aide à garder une sensation fraîche',
    ],
    isActive: true,
  },
  {
    slug: 'bioderma-atoderm-intensive',
    name: 'Atoderm Intensive Baume',
    brand: 'Bioderma',
    description: 'Nourrit intensément. Aide à réduire les tiraillements.',
    imagePath: '/public/products/bioderma-atoderm-intensive.svg',
    productType: 'moisturizer',
    price: '180',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive'],
    goals: ['hydration', 'barrier'],
    keyIngredients: ['Niacinamide', 'Glycérine'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['très sec', 'sans parfum'],
    badges: ['Très sec'],
    benefits: ['Nourrit intensément', 'Aide à réduire les tiraillements'],
    isActive: true,
  },
  {
    slug: 'svr-ampoule-b3',
    name: 'Ampoule B3 Hydra',
    brand: 'SVR',
    description:
      'Hydrate et renforce la barrière. Convient aux routines simples.',
    imagePath: '/public/products/svr-ampoule-b3.svg',
    productType: 'serum',
    price: '230',
    currency: 'MAD',
    skinTypes: ['dry', 'sensitive', 'normal'],
    goals: ['hydration', 'barrier', 'redness'],
    keyIngredients: ['Niacinamide', 'Acide hyaluronique'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['b3', 'barrière'],
    badges: ['Barrière cutanée'],
    benefits: [
      'Hydrate et renforce la barrière',
      'Convient aux routines simples',
    ],
    isActive: true,
  },
  {
    slug: 'vichy-capital-soleil',
    name: 'Capital Soleil UV-Age Daily',
    brand: 'Vichy',
    description: 'Protège des UV. Texture fluide pour le matin.',
    imagePath: '/public/products/vichy-capital-soleil.svg',
    productType: 'spf',
    price: '190',
    currency: 'MAD',
    skinTypes: ['normal', 'combination', 'dry'],
    goals: ['anti_age', 'glow'],
    keyIngredients: ['Peptides', 'Niacinamide', 'Filtres UV'],
    watchoutIngredients: ['Parfum'],
    avoidFor: ['fragrance-sensitive'],
    tags: ['spf', 'anti-âge'],
    badges: ['SPF quotidien'],
    benefits: ['Protège des UV', 'Texture fluide pour le matin'],
    isActive: true,
  },
  {
    slug: 'la-roche-toleriane',
    name: 'Toleriane Sensitive',
    brand: 'La Roche-Posay',
    description: 'Hydrate les peaux sensibles. Routine simple et confortable.',
    imagePath: '/public/products/la-roche-toleriane.svg',
    productType: 'moisturizer',
    price: '155',
    currency: 'MAD',
    skinTypes: ['sensitive', 'normal', 'dry'],
    goals: ['redness', 'barrier', 'hydration'],
    keyIngredients: ['Glycérine', 'Céramide', 'Niacinamide'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['tolérance', 'sans parfum'],
    badges: ['Sensible'],
    benefits: ['Hydrate les peaux sensibles', 'Routine simple et confortable'],
    isActive: true,
  },
  {
    slug: 'ordinary-azelaic-acid',
    name: 'Azelaic Acid Suspension 10%',
    brand: 'The Ordinary',
    description:
      'Aide sur imperfections et rougeurs visibles. Texture à tester progressivement.',
    imagePath: '/public/products/ordinary-azelaic-acid.svg',
    productType: 'treatment',
    price: '115',
    currency: 'MAD',
    skinTypes: ['oily', 'combination', 'normal'],
    goals: ['acne', 'redness', 'glow'],
    keyIngredients: ['Acide azélaïque'],
    watchoutIngredients: [],
    avoidFor: ['very-sensitive'],
    tags: ['teint', 'imperfections'],
    badges: ['Teint irrégulier'],
    benefits: [
      'Aide sur imperfections et rougeurs visibles',
      'Texture à tester progressivement',
    ],
    isActive: true,
  },
  {
    slug: 'neutrogena-retinol-boost',
    name: 'Retinol Boost Night Cream',
    brand: 'Neutrogena',
    description: 'Routine du soir anti-âge. À introduire doucement.',
    imagePath: '/public/products/neutrogena-retinol-boost.svg',
    productType: 'moisturizer',
    price: '170',
    currency: 'MAD',
    skinTypes: ['normal', 'dry', 'combination'],
    goals: ['anti_age', 'glow'],
    keyIngredients: ['Rétinol', 'Acide hyaluronique'],
    watchoutIngredients: ['Rétinol', 'Parfum'],
    avoidFor: [
      'pregnancy',
      'very-sensitive',
      'retinol-beginner',
      'fragrance-sensitive',
    ],
    tags: ['nuit', 'anti-âge'],
    badges: ['Nuit'],
    benefits: ['Routine du soir anti-âge', 'À introduire doucement'],
    isActive: true,
  },
  {
    slug: 'garnier-vitamin-c',
    name: 'Vitamin C Brightening Serum',
    brand: 'Garnier',
    description: 'Aide à illuminer le teint. Cible les taches visibles.',
    imagePath: '/public/products/garnier-vitamin-c.svg',
    productType: 'serum',
    price: '120',
    currency: 'MAD',
    skinTypes: ['normal', 'combination', 'oily'],
    goals: ['glow'],
    keyIngredients: ['Vitamine C', 'Niacinamide', 'Acide salicylique'],
    watchoutIngredients: ['Parfum'],
    avoidFor: ['very-sensitive', 'fragrance-sensitive'],
    tags: ['éclat', 'taches'],
    badges: ['Éclat'],
    benefits: ['Aide à illuminer le teint', 'Cible les taches visibles'],
    isActive: true,
  },
  {
    slug: 'cerave-am-facial',
    name: 'AM Facial Moisturizing Lotion SPF',
    brand: 'CeraVe',
    description: 'Hydratant avec SPF. Aide la barrière cutanée.',
    imagePath: '/public/products/cerave-am-facial.svg',
    productType: 'spf',
    price: '160',
    currency: 'MAD',
    skinTypes: ['normal', 'dry', 'sensitive'],
    goals: ['hydration', 'barrier'],
    keyIngredients: ['Céramides', 'Niacinamide', 'Filtres UV'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['spf', 'sans parfum'],
    badges: ['Matin'],
    benefits: ['Hydratant avec SPF', 'Aide la barrière cutanée'],
    isActive: true,
  },
  {
    slug: 'avene-tolerance-control',
    name: 'Tolérance Control Crème',
    brand: 'Avène',
    description:
      'Apaise rapidement les peaux réactives. Formule courte et confortable.',
    imagePath: '/public/products/avene-tolerance-control.svg',
    productType: 'moisturizer',
    price: '180',
    currency: 'MAD',
    skinTypes: ['sensitive', 'dry', 'normal'],
    goals: ['redness', 'barrier'],
    keyIngredients: ['D-Sensinose', 'Eau thermale'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['minimaliste', 'apaisant'],
    badges: ['Tolérance'],
    benefits: [
      'Apaise rapidement les peaux réactives',
      'Formule courte et confortable',
    ],
    isActive: true,
  },
  {
    slug: 'bioderma-pigmentbio',
    name: 'Pigmentbio C-Concentrate',
    brand: 'Bioderma',
    description: 'Cible les taches visibles. Lisse le teint progressivement.',
    imagePath: '/public/products/bioderma-pigmentbio.svg',
    productType: 'serum',
    price: '260',
    currency: 'MAD',
    skinTypes: ['normal', 'combination', 'oily'],
    goals: ['glow', 'anti_age'],
    keyIngredients: ['Vitamine C', 'Acide glycolique', 'Niacinamide'],
    watchoutIngredients: ['AHA'],
    avoidFor: ['very-sensitive', 'retinol-beginner'],
    tags: ['taches', 'éclat'],
    badges: ['Taches'],
    benefits: ['Cible les taches visibles', 'Lisse le teint progressivement'],
    isActive: true,
  },
  {
    slug: 'vichy-normaderm',
    name: 'Normaderm Phytosolution',
    brand: 'Vichy',
    description: 'Aide à réduire les imperfections. Hydrate légèrement.',
    imagePath: '/public/products/vichy-normaderm.svg',
    productType: 'serum',
    price: '210',
    currency: 'MAD',
    skinTypes: ['oily', 'combination'],
    goals: ['acne', 'oil_control'],
    keyIngredients: ['Acide salicylique', 'Probiotique', 'Acide hyaluronique'],
    watchoutIngredients: ['Acide salicylique'],
    avoidFor: ['very-sensitive'],
    tags: ['imperfections'],
    badges: ['Anti-imperfections'],
    benefits: ['Aide à réduire les imperfections', 'Hydrate légèrement'],
    isActive: true,
  },
  {
    slug: 'eucerin-anti-pigment',
    name: 'Anti-Pigment Dual Serum',
    brand: 'Eucerin',
    description:
      'Cible les taches brunes. Uniformise progressivement le teint.',
    imagePath: '/public/products/eucerin-anti-pigment.svg',
    productType: 'serum',
    price: '320',
    currency: 'MAD',
    skinTypes: ['normal', 'dry', 'combination'],
    goals: ['glow', 'anti_age'],
    keyIngredients: ['Thiamidol', 'Acide hyaluronique'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['taches', 'teint'],
    badges: ['Taches pigmentaires'],
    benefits: [
      'Cible les taches brunes',
      'Uniformise progressivement le teint',
    ],
    isActive: true,
  },
  {
    slug: 'svr-sensifine',
    name: 'Sensifine Hydra-Crème',
    brand: 'SVR',
    description:
      'Hydrate les peaux intolérantes. Formule pensée pour la tolérance.',
    imagePath: '/public/products/svr-sensifine.svg',
    productType: 'moisturizer',
    price: '145',
    currency: 'MAD',
    skinTypes: ['sensitive', 'dry', 'normal'],
    goals: ['redness', 'hydration', 'barrier'],
    keyIngredients: ['Niacinamide', 'Huile de coton'],
    watchoutIngredients: [],
    avoidFor: [],
    tags: ['minimaliste', 'sensible'],
    badges: ['Peau réactive'],
    benefits: [
      'Hydrate les peaux intolérantes',
      'Formule pensée pour la tolérance',
    ],
    isActive: true,
  },
];
